import type { WCProduct, WCCategory } from "./woocommerce";

export const mockCategories: WCCategory[] = [
  { id: 1, name: "শস্য ও চাল", slug: "grains-rice", description: "দেশীয় জৈব শস্য", count: 12, image: null },
  { id: 2, name: "তেল ও ঘি", slug: "oils-ghee", description: "খাঁটি দেশীয় তেল", count: 8, image: null },
  { id: 3, name: "মসলা", slug: "spices", description: "খাঁটি মসলা", count: 20, image: null },
  { id: 4, name: "মধু ও মিষ্টি", slug: "honey-sweets", description: "প্রাকৃতিক মধু", count: 6, image: null },
  { id: 5, name: "শাকসবজি", slug: "vegetables", description: "জৈব শাকসবজি", count: 15, image: null },
  { id: 6, name: "ডাল ও বাদাম", slug: "pulses-nuts", description: "দেশীয় ডাল", count: 10, image: null },
];

export const mockProducts: WCProduct[] = [
  {
    id: 1,
    name: "কালিজিরা চাল",
    slug: "kalijira-rice",
    description: "সুনামগঞ্জের হাওর থেকে সংগ্রহ করা বিশুদ্ধ কালিজিরা চাল। কোনো কৃত্রিম সার বা কীটনাশক ছাড়াই চাষ করা হয়েছে।",
    short_description: "হাওরের খাঁটি কালিজিরা চাল — সুগন্ধি ও পুষ্টিকর",
    price: "180",
    regular_price: "200",
    sale_price: "180",
    on_sale: true,
    stock_status: "instock",
    stock_quantity: 50,
    images: [{ id: 1, src: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&q=80", alt: "কালিজিরা চাল" }],
    categories: [{ id: 1, name: "শস্য ও চাল", slug: "grains-rice" }],
    tags: [],
    average_rating: "4.8",
    rating_count: 124,
    meta_data: [],
  },
  {
    id: 2,
    name: "সরিষার তেল",
    slug: "mustard-oil",
    description: "ঘানি ভাঙ্গা খাঁটি সরিষার তেল। কোনো ভেজাল নেই, রাসায়নিক পরিশোধন নেই।",
    short_description: "ঘানি ভাঙ্গা খাঁটি সরিষার তেল",
    price: "320",
    regular_price: "320",
    sale_price: "",
    on_sale: false,
    stock_status: "instock",
    stock_quantity: 30,
    images: [{ id: 2, src: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80", alt: "সরিষার তেল" }],
    categories: [{ id: 2, name: "তেল ও ঘি", slug: "oils-ghee" }],
    tags: [],
    average_rating: "4.9",
    rating_count: 89,
    meta_data: [],
  },
  {
    id: 3,
    name: "সুন্দরবনের মধু",
    slug: "sundarbans-honey",
    description: "সুন্দরবন থেকে সংগৃহীত খাঁটি প্রাকৃতিক মধু। কোনো চিনি বা কৃত্রিম মিষ্টি মেশানো নেই।",
    short_description: "সুন্দরবনের প্রাকৃতিক বন-মধু",
    price: "650",
    regular_price: "750",
    sale_price: "650",
    on_sale: true,
    stock_status: "instock",
    stock_quantity: 20,
    images: [{ id: 3, src: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&q=80", alt: "সুন্দরবনের মধু" }],
    categories: [{ id: 4, name: "মধু ও মিষ্টি", slug: "honey-sweets" }],
    tags: [],
    average_rating: "5.0",
    rating_count: 203,
    meta_data: [],
  },
  {
    id: 4,
    name: "হলুদ গুঁড়া",
    slug: "turmeric-powder",
    description: "কুষ্টিয়ার বিখ্যাত হলুদ থেকে তৈরি বিশুদ্ধ হলুদ গুঁড়া। রঙ মেশানো নেই।",
    short_description: "খাঁটি হলুদ গুঁড়া — কোনো রঙ নেই",
    price: "120",
    regular_price: "120",
    sale_price: "",
    on_sale: false,
    stock_status: "instock",
    stock_quantity: 100,
    images: [{ id: 4, src: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=600&q=80", alt: "হলুদ গুঁড়া" }],
    categories: [{ id: 3, name: "মসলা", slug: "spices" }],
    tags: [],
    average_rating: "4.7",
    rating_count: 156,
    meta_data: [],
  },
  {
    id: 5,
    name: "গাওয়া ঘি",
    slug: "gaoa-ghee",
    description: "দেশীয় গরুর দুধ থেকে তৈরি বিশুদ্ধ গাওয়া ঘি। ঐতিহ্যবাহী পদ্ধতিতে প্রস্তুত।",
    short_description: "দেশী গরুর খাঁটি গাওয়া ঘি",
    price: "980",
    regular_price: "1100",
    sale_price: "980",
    on_sale: true,
    stock_status: "instock",
    stock_quantity: 15,
    images: [{ id: 5, src: "https://images.unsplash.com/photo-1600180758890-6b94519a8ba6?w=600&q=80", alt: "গাওয়া ঘি" }],
    categories: [{ id: 2, name: "তেল ও ঘি", slug: "oils-ghee" }],
    tags: [],
    average_rating: "4.9",
    rating_count: 78,
    meta_data: [],
  },
  {
    id: 6,
    name: "লাল মসুর ডাল",
    slug: "red-lentils",
    description: "রাজশাহী থেকে আনা খাঁটি দেশীয় লাল মসুর ডাল। কোনো রাসায়নিক পালিশ নেই।",
    short_description: "দেশীয় লাল মসুর ডাল — রাজশাহী থেকে",
    price: "140",
    regular_price: "140",
    sale_price: "",
    on_sale: false,
    stock_status: "instock",
    stock_quantity: 80,
    images: [{ id: 6, src: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&q=80", alt: "মসুর ডাল" }],
    categories: [{ id: 6, name: "ডাল ও বাদাম", slug: "pulses-nuts" }],
    tags: [],
    average_rating: "4.6",
    rating_count: 92,
    meta_data: [],
  },
  {
    id: 7,
    name: "নারকেল তেল",
    slug: "coconut-oil",
    description: "বরিশালের তাজা নারকেল থেকে ঠান্ডা চাপে তৈরি বিশুদ্ধ নারকেল তেল।",
    short_description: "ঠান্ডা চাপে তৈরি খাঁটি নারকেল তেল",
    price: "420",
    regular_price: "480",
    sale_price: "420",
    on_sale: true,
    stock_status: "instock",
    stock_quantity: 25,
    images: [{ id: 7, src: "https://images.unsplash.com/photo-1519624014191-508652f24d4f?w=600&q=80", alt: "নারকেল তেল" }],
    categories: [{ id: 2, name: "তেল ও ঘি", slug: "oils-ghee" }],
    tags: [],
    average_rating: "4.8",
    rating_count: 67,
    meta_data: [],
  },
  {
    id: 8,
    name: "জৈব পালং শাক",
    slug: "organic-spinach",
    description: "রাসায়নিক সার ও কীটনাশকমুক্ত জৈব পালং শাক। সরাসরি কৃষকের খামার থেকে।",
    short_description: "তাজা জৈব পালং শাক — কৃষকের খামার থেকে",
    price: "60",
    regular_price: "60",
    sale_price: "",
    on_sale: false,
    stock_status: "instock",
    stock_quantity: 200,
    images: [{ id: 8, src: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&q=80", alt: "পালং শাক" }],
    categories: [{ id: 5, name: "শাকসবজি", slug: "vegetables" }],
    tags: [],
    average_rating: "4.5",
    rating_count: 45,
    meta_data: [],
  },
];
